spring:
  datasource:
    url: jdbc:postgresql://<host-prod>:5432/payapi_prod
    username: prod_user
    password: prod_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

kafka:
  bootstrap-servers: localhost:9092
  topic: pagamentos-prod
