spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay_dev
    username: picpay
    password: picpay
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9093
    consumer:
      group-id: payapi-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      max-request-size: 20000000
  kafka-connect:
    image: debezium/connect:2.6
    container_name: kafka-connect
    depends_on:
      - kafka
      - postgres-dev
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: http://localhost:9092
      GROUP_ID: debezium
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER_SCHEMAS_ENABLE: false
      VALUE_CONVERTER_SCHEMAS_ENABLE: false
      PLUGIN_PATH: /kafka/connect

    networks:
      - payapi-net
kafka:
  topic: pagamentos


